name: CI

on:
  pull_request:
    types: [opened, synchronize]
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10" , "3.11", "3.12", "3.13"]

    steps:
        - uses: actions/checkout@v4

        - name: Setup the environment
          uses: ./.github/actions/build_env
          with:
            python-version: ${{ matrix.python-version }}

        - name: Run tests
          run: |
            uv run pytest --cov=pyinsurance --cov-report=xml

  lint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - name: Setup the environment
          uses: ./.github/actions/build_env

        - name: Run flake8
          run: |
            uv run flake8 pyinsurance/ test/

        - name: Run black
          run: |
            uv run black --check pyinsurance/ test/

        - name: Run isort
          run: |
            uv run isort --check-only pyinsurance/ test/

  static-analysis:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - name: Setup the environment
          uses: ./.github/actions/build_env

        - name: Run static analysis
          run: |
            uv run mypy pyinsurance
